# Generated by Django 5.2.15 on 2026-08-24 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('faculty_name', models.CharField(default='Faculty', max_length=100)),
                ('department_name', models.CharField(blank=True, default='FoS', max_length=100)),
                ('course_name', models.CharField(blank=True, default='Computer Science', max_length=100)),
                ('degree_name', models.CharField(blank=True, default='MCA', max_length=50)),
                ('semester', models.CharField(default='Semester 3', max_length=50)),
                ('division', models.CharField(default='22', max_length=50)),
                ('subject', models.CharField(blank=True, default='AI & Machine Learning', max_length=100)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='attendance_sessions/original/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='attendance_sessions/annotated/')),
                ('total_detected_faces', models.IntegerField(default=0)),
                ('total_matched_students', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='e.g. FoS (Faculty of Science)', max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Computer Science', max_length=100)),
                ('degree', models.CharField(blank=True, help_text='e.g. MCA, BCA, B.Tech', max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance_app.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(default='Semester 3', max_length=50)),
                ('division', models.CharField(default='22', max_length=50)),
                ('photo', models.ImageField(upload_to='students/profile_photos/')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.department')),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Recognition confidence percentage')),
                ('detected_thumbnail', models.TextField(blank=True, help_text='Base64 or URL of detected face crop', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance_app.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_app.student')),
            ],
            options={
                'ordering': ['student__roll_no'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
